---
- name: "Customize: Debug bsd_cimage_debug={{ bsd_cimage_debug }}"
  vars:
    msg: |-
      bsd_cimage_mount_path: {{ bsd_cimage_mount_path }}
      bsd_cimage_loaderconf: {{ bsd_cimage_loaderconf }}
      bsd_cimage_rcconf: {{ bsd_cimage_rcconf }}
      bsd_cimage_wpasupconf: {{ bsd_cimage_wpasupconf }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: bsd_cimage_debug | bool

- name: Include fn/loaderconf.yml
  ansible.builtin.include_tasks: fn/loaderconf.yml
  when: bsd_cimage_loaderconf | bool
  tags: bsd_cimage_loaderconf

- name: Include fn/rcconf.yml
  ansible.builtin.include_tasks: fn/rcconf.yml
  when: bsd_cimage_rcconf | bool
  tags: bsd_cimage_rcconf

- name: Include fn/wpasupconf.yml
  ansible.builtin.include_tasks: fn/wpasupconf.yml
  when: bsd_cimage_wpasupconf | bool
  tags: bsd_cimage_wpasupconf

# TODO: firstboot, wpa_cli

# EOF
