---
- name: "Customize: Debug bsd_cimage_debug={{ bsd_cimage_debug }}"
  when: bsd_cimage_debug | bool
  vars:
    msg: |-
      bsd_cimage_mount_path: {{ bsd_cimage_mount_path }}
      bsd_cimage_loaderconf: {{ bsd_cimage_loaderconf }}
      bsd_cimage_rcconf: {{ bsd_cimage_rcconf }}
      bsd_cimage_wpasupconf: {{ bsd_cimage_wpasupconf }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: Include fn/loaderconf.yml
  when: bsd_cimage_loaderconf | bool
  tags: bsd_cimage_loaderconf
  ansible.builtin.include_tasks: fn/loaderconf.yml

- name: Include fn/rcconf.yml
  when: bsd_cimage_rcconf | bool
  tags: bsd_cimage_rcconf
  ansible.builtin.include_tasks: fn/rcconf.yml

- name: Include fn/wpasupconf.yml
  when: bsd_cimage_wpasupconf | bool
  tags: bsd_cimage_wpasupconf
  ansible.builtin.include_tasks: fn/wpasupconf.yml

# TODO: firstboot, wpa_cli

# EOF
