---
- name: "Customize: Debug cimage_debug={{ cimage_debug }}"
  when: cimage_debug | bool
  ansible.builtin.debug:
    var:
      cimage_customize

- name: Customize image.
  ansible.builtin.include_tasks: "fn/{{ customize_item }}.yml"
  loop: "{{ cimage_customize | dict2items | selectattr('value') | map(attribute='key') }}"
  loop_control:
    loop_var: customize_item

# EOF
