---
- name: "Debug cimage_debug={ cimage_debug }}"
  vars:
    msg: |-
      cimage_role_version: {{ cimage_role_version }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      ansible_architecture: {{ ansible_architecture }}
      ansible_os_family: {{ ansible_os_family }}
      ansible_distribution: {{ ansible_distribution }}
      ansible_distribution_major_version: {{ ansible_distribution_major_version }}
      ansible_distribution_version: {{ ansible_distribution_version }}
      ansible_distribution_release: {{ ansible_distribution_release }}
      ansible_python_version: {{ ansible_python_version }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      freebsd_install_retries: {{ freebsd_install_retries }}
      freebsd_install_delay: {{ freebsd_install_delay }}
      cimage_install: {{ cimage_install }}
      cimage_pkgng_rootdir: {{ cimage_pkgng_rootdir }}
      cimage_pkgng_use_globs: {{ cimage_pkgng_use_globs }}
      cimage_pkgng_chroot: {{ cimage_pkgng_chroot | d('UNDEFINED') }}
      cimage_pkgng_cached: {{ cimage_pkgng_cached | d('UNDEFINED') }}
      cimage_pkgng_ignore_osver: {{ cimage_pkgng_ignore_osver | d('UNDEFINED') }}
      cimage_pkgng_pkgsite: {{ cimage_pkgng_pkgsite | d('UNDEFINED') }}
      cimage_packages:
        {{ cimage_packages | to_nice_yaml(indent=2) | indent(2) }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      cimage_sanity: {{ cimage_sanity }}
      cimage_sanity_quiet: {{ cimage_sanity_quiet }}
      cimage_mount: {{ cimage_mount }}
      cimage_umount: {{ cimage_umount }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      cimage_get_images: {{ cimage_get_images }}
      cimage_get_checksums: {{ cimage_get_checksums }}
      cimage_dir: {{ cimage_dir }}
      cimage_owner: {{ cimage_owner | d('UNDEFINED') }}
      cimage_group: {{ cimage_group | d('UNDEFINED') }}
      cimage_mode: {{ cimage_mode | d('UNDEFINED') }}
      cimage_mode_dir: {{ cimage_mode_dir | d('UNDEFINED') }}
      cimage_download:
        {{ cimage_download | to_nice_yaml(indent=2) | indent(2) }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      cimage_unpack: {{ cimage_unpack }}
      cimage_unpack_cmd:
        {{ cimage_unpack_cmd | to_yaml(indent=2) | indent(2) }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      cimage_mount_dir: {{ cimage_mount_dir }}
      cimage_mount_file: {{ cimage_mount_file }}
      cimage_mount_mode: {{ cimage_mount_mode }}
      cimage_mount_points_create: {{ cimage_mount_points_create }}
      cimage_mount_points:
        {{ cimage_mount_points | to_yaml(indent=2) | indent(2) }}
      cimage_mount_path: {{ cimage_mount_path }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      cimage_loaderconf: {{ cimage_loaderconf }}
      cimage_loaderconf_backup: {{ cimage_loaderconf_backup }}
      cimage_loaderconf_modules:
        {{ cimage_loaderconf_modules | to_yaml(indent=2) | indent(2) }}
      cimage_loaderconf_data:
        {{ cimage_loaderconf_data | to_nice_yaml(indent=2) | indent(2) }}
      cimage_loaderconf_sysctl:
        {{ cimage_loaderconf_sysctl | to_nice_yaml(indent=2) | indent(2) }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      cimage_rcconf: {{ cimage_rcconf }}
      cimage_rcconf_backup: {{ cimage_rcconf_backup }}
      cimage_rcconf_data:
        {{ cimage_rcconf_data | to_yaml(indent=2) | indent(2) }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      cimage_wpasupconf: {{ cimage_wpasupconf }}
      cimage_wpasupconf_backup: {{ cimage_wpasupconf_backup }}
      cimage_wpasupconf_file: {{ cimage_wpasupconf_file }}
      cimage_wpasupconf_owner: {{ cimage_wpasupconf_owner }}
      cimage_wpasupconf_group: {{ cimage_wpasupconf_group }}
      cimage_wpasupconf_mode: {{ cimage_wpasupconf_mode }}
      cimage_wpasupconf_global:
        {{ cimage_wpasupconf_global | to_nice_yaml(indent=2) | indent(2) }}
      {% if cimage_debug_classified %}
      cimage_wpasupconf_data:
        {{ cimage_wpasupconf_data | to_nice_yaml(indent=2) | indent(2) }}
      {% endif %}
      cimage_wpasupconf_link: {{ cimage_wpasupconf_link }}
      cimage_wpasupconf_link_dev: {{ cimage_wpasupconf_link_dev }}
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
