---

- name: "Debug"
  vars:
    msg: |
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         ansible_architecture [{{ ansible_architecture }}]
         ansible_os_family [{{ ansible_os_family }}]
         ansible_distribution [{{ ansible_distribution }}]
         ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
         ansible_distribution_version [{{ ansible_distribution_version }}]
         ansible_distribution_release [{{ ansible_distribution_release }}]
         ansible_python_version [{{ ansible_python_version }}]
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         freebsd_install_method [{{ freebsd_install_method }}]
         freebsd_use_packages [{{ freebsd_use_packages }}]
         freebsd_install_retries [{{ freebsd_install_retries }}]
         freebsd_install_delay [{{ freebsd_install_delay }}]

         bsd_cimage_sanity [{{ bsd_cimage_sanity }}]
         bsd_cimage_mount [{{ bsd_cimage_mount }}]
         bsd_cimage_umount [{{ bsd_cimage_umount }}]
         bsd_cimage_install [{{ bsd_cimage_install }}]
         bsd_cimage_packages
         {{ bsd_cimage_packages|to_nice_yaml }}
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         bsd_cimage_dir [{{ bsd_cimage_dir }}]
         bsd_cimage_owner [{{ bsd_cimage_owner|default('UNDEFINED') }}]
         bsd_cimage_group [{{ bsd_cimage_group|default('UNDEFINED') }}]
         bsd_cimage_mode [{{ bsd_cimage_mode|default('UNDEFINED') }}]
         bsd_cimage_download
         {{ bsd_cimage_download|to_nice_yaml }}
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         bsd_cimage_mount_dir [{{ bsd_cimage_mount_dir }}]
         bsd_cimage_mount_file [{{ bsd_cimage_mount_file }}]
         bsd_cimage_mount_mode [{{ bsd_cimage_mount_mode }}]
         bsd_cimage_mount_points_create [{{ bsd_cimage_mount_points_create }}]
         bsd_cimage_mount_points
         {{ bsd_cimage_mount_points|to_yaml }}
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         bsd_cimage_mount_path [{{ bsd_cimage_mount_path }}
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         bsd_cimage_loaderconf [{{ bsd_cimage_loaderconf }}]
         bsd_cimage_loaderconf_backup [{{ bsd_cimage_loaderconf_backup }}]
         bsd_cimage_loaderconf_modules
         {{ bsd_cimage_loaderconf_modules|to_yaml }}
         bsd_cimage_loaderconf_data
         {{ bsd_cimage_loaderconf_data|to_nice_yaml }}
         bsd_cimage_loaderconf_sysctl
         {{ bsd_cimage_loaderconf_sysctl|to_nice_yaml }}
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         bsd_cimage_rcconf [{{ bsd_cimage_rcconf }}]
         bsd_cimage_rcconf_backup [{{ bsd_cimage_rcconf_backup }}]
         bsd_cimage_rcconf_data
         {{ bsd_cimage_rcconf_data|to_yaml }}
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         bsd_cimage_wpasupconf [{{ bsd_cimage_wpasupconf }}]
         bsd_cimage_wpasupconf_backup [{{ bsd_cimage_wpasupconf_backup }}]
         bsd_cimage_wpasupconf_file [{{ bsd_cimage_wpasupconf_file }}]
         bsd_cimage_wpasupconf_owner [{{ bsd_cimage_wpasupconf_owner }}]
         bsd_cimage_wpasupconf_group [{{ bsd_cimage_wpasupconf_group }}]
         bsd_cimage_wpasupconf_mode [{{ bsd_cimage_wpasupconf_mode }}]
         bsd_cimage_wpasupconf_global
         {{ bsd_cimage_wpasupconf_global|to_nice_yaml }}
         {% if bsd_cimage_debug_classified %}
         bsd_cimage_wpasupconf_data
         {{ bsd_cimage_wpasupconf_data|to_nice_yaml }}
         {% endif %}
         bsd_cimage_wpasupconf_link [{{ bsd_cimage_wpasupconf_link }}]
         bsd_cimage_wpasupconf_link_dev [{{ bsd_cimage_wpasupconf_link_dev }}]
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  debug:
    msg: "{{ msg.split('\n')[:-1] }}"

# EOF
...
