---
- name: "Download: Debug bsd_cimage_debug={{ bsd_cimage_debug }}"
  vars:
    msg: |-
      bsd_cimage_download:
        {{ bsd_cimage_download | to_nice_yaml(indent=2) | indent(2) }}
      bsd_cimage_dir: {{ bsd_cimage_dir }}
      bsd_cimage_owner: {{ bsd_cimage_owner | d('UNDEFINED') }}
      bsd_cimage_group: {{ bsd_cimage_group | d('UNDEFINED') }}
      bsd_cimage_mode: {{ bsd_cimage_mode | d('UNDEFINED') }}
      bsd_cimage_get_checksums: {{ bsd_cimage_get_checksums }}
      bsd_cimage_get_images: {{ bsd_cimage_get_images }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: bsd_cimage_debug | bool

- name: Checksums
  when: bsd_cimage_get_checksums | bool
  block:

    - name: "Download: Get checksums"
      ansible.builtin.get_url:
        url: "{{ [item.site, item.checksum] | community.general.path_join }}"
        dest: "{{ [bsd_cimage_dir, item.checksum] | community.general.path_join }}"
        owner: "{{ bsd_cimage_owner | d(omit) }}"
        group: "{{ bsd_cimage_group | d(omit) }}"
        mode: "{{ bsd_cimage_mode | d(omit) }}"
      loop: "{{ bsd_cimage_download }}"
      loop_control:
        label: "{{ item.checksum }}"

    - name: "Download: Read checksums"
      ansible.builtin.command:
        cmd: >
          cat {{ [bsd_cimage_dir, item.checksum] | community.general.path_join }}
      register: cresult
      loop: "{{ bsd_cimage_download }}"
      loop_control:
        label: "{{ item.checksum }}"
      changed_when: false
      check_mode: false

    - name: "Download: Debug checksums bsd_cimage_debug={{ bsd_cimage_debug }}"
      ansible.builtin.debug:
        msg: "{{ algorithm }}:{{ checksum }}"
      loop: "{{ bsd_cimage_download }}"
      loop_control:
        label: "{{ item.image }}"
        extended: true
      vars:
        algorithm: "{{ cresult.results[ansible_loop.index0].stdout.split() | first | lower }}"
        checksum: "{{ cresult.results[ansible_loop.index0].stdout.split() | last }}"
      when:
        - bsd_cimage_debug | bool
        - cresult.results[ansible_loop.index0].stdout is defined

- name: Images
  when: bsd_cimage_get_images | bool
  block:

    - name: "Download: Get images"
      ansible.builtin.get_url:
        url: "{{ [item.site, item.image] | community.general.path_join }}"
        checksum: "{{ algorithm }}:{{ checksum }}"
        dest: "{{ [bsd_cimage_dir, item.image] | community.general.path_join }}"
        owner: "{{ bsd_cimage_owner | d(omit) }}"
        group: "{{ bsd_cimage_group | d(omit) }}"
        mode: "{{ bsd_cimage_mode | d(omit) }}"
      register: gresult
      loop: "{{ bsd_cimage_download }}"
      loop_control:
        label: "{{ item.image }}"
        extended: true
      vars:
        algorithm: "{{ cresult.results[ansible_loop.index0].stdout.split() | first | lower }}"
        checksum: "{{ cresult.results[ansible_loop.index0].stdout.split() | last }}"
      when: cresult.results[ansible_loop.index0].stdout is defined

    - name: "Download: Debug images bsd_cimage_debug={{ bsd_cimage_debug }}"
      ansible.builtin.debug:
        var: gresult
      when: bsd_cimage_debug | bool

# EOF
