---

- name: "download: Debug"
  vars:
    msg: |-
      bsd_cimage_download
      {{ bsd_cimage_download|to_nice_yaml }}
      bsd_cimage_dir [{{ bsd_cimage_dir }}]
      bsd_cimage_owner [{{ bsd_cimage_owner|default('UNDEFINED') }}]
      bsd_cimage_group [{{ bsd_cimage_group|default('UNDEFINED') }}]
      bsd_cimage_mode [{{ bsd_cimage_mode|default('UNDEFINED') }}]
      bsd_cimage_get_checksums [{{ bsd_cimage_get_checksums|default(true) }}]
      bsd_cimage_get_images [{{ bsd_cimage_get_images|default(true) }}]
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: bsd_cimage_debug|bool

- name: "download: Get checksums"
  ansible.builtin.get_url:
    url: "{{ [item.site, item.checksum]|community.general.path_join }}"
    dest: "{{ bsd_cimage_dir }}/{{ item.checksum }}"
    owner: "{{ bsd_cimage_owner|default(omit) }}"
    group: "{{ bsd_cimage_group|default(omit) }}"
    mode: "{{ bsd_cimage_mode|default(omit) }}"
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.checksum }}"
  when: bsd_cimage_get_checksums|default(true)|bool

- name: "download: Read checksums"
  ansible.builtin.command:
    cmd: >
      cat {{ bsd_cimage_dir }}/{{ item.checksum }}
  register: cresult
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.checksum }}"
  changed_when: false
  check_mode: false

- name: "download: Debug checksums"
  ansible.builtin.debug:
    msg: "{{ algorithm }}:{{ checksum }}"
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.image }}"
    extended: true
  vars:
    algorithm: "{{ cresult.results[ansible_loop.index0].stdout.split()|first|lower }}"
    checksum: "{{ cresult.results[ansible_loop.index0].stdout.split()|last }}"
  when:
    - bsd_cimage_debug|bool
    - cresult.results[ansible_loop.index0].stdout is defined

- name: "download: Get images"
  ansible.builtin.get_url:
    url: "{{ [item.site, item.image]|community.general.path_join }}"
    checksum: "{{ algorithm }}:{{ checksum }}"
    dest: "{{ bsd_cimage_dir }}/{{ item.image }}"
    owner: "{{ bsd_cimage_owner|default(omit) }}"
    group: "{{ bsd_cimage_group|default(omit) }}"
    mode: "{{ bsd_cimage_mode|default(omit) }}"
  register: gresult
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.image }}"
    extended: true
  vars:
    algorithm: "{{ cresult.results[ansible_loop.index0].stdout.split()|first|lower }}"
    checksum: "{{ cresult.results[ansible_loop.index0].stdout.split()|last }}"
  when:
    - bsd_cimage_get_images|default(true)|bool
    - cresult.results[ansible_loop.index0].stdout is defined

- name: "download: Debug images"
  ansible.builtin.debug:
    var: gresult
  when: bsd_cimage_debug|bool

# TODO:
# 1) Extract item.image; keep the input file (-k)
#    xz -d -k FreeBSD-12.2-STABLE-arm-armv6-RPI-B-20210107-r368787.img.xz
# 2) Link to sorted dirs
# 3) Copy to live

# EOF
...
