---

- name: "download: Debug"
  vars:
    msg: |
      bsd_cimage_download
      {{ bsd_cimage_download|to_nice_yaml }}
      bsd_cimage_dir [{{ bsd_cimage_dir }}]
      bsd_cimage_owner [{{ bsd_cimage_owner|default('UNDEFINED') }}]
      bsd_cimage_group [{{ bsd_cimage_group|default('UNDEFINED') }}]
      bsd_cimage_mode [{{ bsd_cimage_mode|default('UNDEFINED') }}]
      bsd_cimage_get_checksums [{{ bsd_cimage_get_checksums|default(true) }}]
      bsd_cimage_get_images [{{ bsd_cimage_get_images|default(true) }}]
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
  when: bsd_cimage_debug|bool

- name: "download: Get checksums"
  get_url:
    url: "{{ item.site ~ '/' ~ item.checksum }}"
    dest: "{{ bsd_cimage_dir }}/{{ item.checksum }}"
    owner: "{{ bsd_cimage_owner|default(omit) }}"
    group: "{{ bsd_cimage_group|default(omit) }}"
    mode: "{{ bsd_cimage_mode|default(omit) }}"
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.checksum }}"
  when: bsd_cimage_get_checksums|default(true)|bool

- name: "download: Read checksums"
  command: "cat {{ bsd_cimage_dir }}/{{ item.checksum }}"
  register: cresult
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.checksum }}"
  changed_when: false

- name: "download: Debug checksums"
  debug:
    msg: "{{ algorithm }}:{{ checksum }}"
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.image }}"
    extended: true
  vars:
    algorithm: "{{ cresult.results[ansible_loop.index0].stdout.split()|first|lower }}"
    checksum: "{{ cresult.results[ansible_loop.index0].stdout.split()|last }}"
  when: bsd_cimage_debug|bool

- name: "download: Get images"
  get_url:
    url: "{{ item.site ~ '/' ~ item.image }}"
    checksum: "{{ algorithm }}:{{ checksum }}"
    dest: "{{ bsd_cimage_dir }}/{{ item.image }}"
    owner: "{{ bsd_cimage_owner|default(omit) }}"
    group: "{{ bsd_cimage_group|default(omit) }}"
    mode: "{{ bsd_cimage_mode|default(omit) }}"
  register: gresult
  loop: "{{ bsd_cimage_download }}"
  loop_control:
    label: "{{ item.image }}"
    extended: true
  vars:
    algorithm: "{{ cresult.results[ansible_loop.index0].stdout.split()|first|lower }}"
    checksum: "{{ cresult.results[ansible_loop.index0].stdout.split()|last }}"
  when: bsd_cimage_get_images|default(true)|bool

- name: "download: Debug images"
  debug:
    msg: "{{ gresult }}"
  when: bsd_cimage_debug|bool

# TODO:
# 1) Extract item.image; keep the input file (-k)
#    xz -d -k FreeBSD-12.2-STABLE-arm-armv6-RPI-B-20210107-r368787.img.xz
# 2) Link to sorted dirs
# 3) Copy to live

# EOF
...
