---
# tasks for freebsd_custom_image

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: bsd_cimage_debug | bool
  tags: bsd_cimage_debug

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: bsd_cimage_install | bool
  tags: bsd_cimage_packages

- name: Import sanity.yml
  ansible.builtin.import_tasks: sanity.yml
  when: bsd_cimage_sanity | bool
  tags: [bsd_cimage_sanity, always]

- name: Import download.yml
  ansible.builtin.import_tasks: download.yml
  tags: bsd_cimage_download

- name: Import unpack.yml
  ansible.builtin.import_tasks: unpack.yml
  when: bsd_cimage_unpack | bool
  tags: bsd_cimage_unpack

- name: Import mount.yml
  ansible.builtin.import_tasks: mount.yml
  when: bsd_cimage_mount | bool
  tags: bsd_cimage_mount

- name: Import customize.yml
  ansible.builtin.import_tasks: customize.yml
  tags: bsd_cimage_customize

- name: Import umount.yml
  ansible.builtin.import_tasks: umount.yml
  when: bsd_cimage_umount | bool
  tags: bsd_cimage_umount

# EOF
