---
- name: "Mount: Debug cimage_debug={{ cimage_debug }}"
  when: cimage_debug | bool
  vars:
    msg: |-
      cimage_mount_dir: {{ cimage_mount_dir }}
      cimage_mount_file: {{ cimage_mount_file }}
      cimage_mount_mode: {{ cimage_mount_mode }}
      cimage_mount_points_create: {{ cimage_mount_points_create }}
      cimage_mount_points:
        {{ cimage_mount_points | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Mount: Create mount points"
  when: cimage_mount_points_create | bool # Note 2.
  tags: cimage_mount_points
  ansible.builtin.file:
    state: directory
    path: "{{ item.mountpoint }}"
    mode: "{{ cimage_mount_mode }}"
  loop: "{{ cimage_mount_points }}"

- name: "Mount: Attach memory disk" # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_mdconfig.yml
  vars:
    al_mdconfig_file: "{{ cimage_mount_dir }}/{{ cimage_mount_file }}"

- name: "Mount: Set variable cimage_mount_dev"
  tags: cimage_mdconfig
  ansible.builtin.set_fact:
    cimage_mount_dev: md{{ al_mdconfig_devs[my_file]['unit'] | d('UNDEFINED') }}
  vars:
    my_file: "{{ cimage_mount_dir }}/{{ cimage_mount_file }}"

- name: "Mount: Debug {{ cimage_mount_dir ~ '/' ~ cimage_mount_file }}"
  when: cimage_debug | bool
  tags: cimage_mdconfig
  ansible.builtin.debug:
    msg: "Mounted at: {{ cimage_mount_dev }}"

- name: "Mount: Mount partitions {{ cimage_mount_dev }}"
  register: result
  ansible.posix.mount:
    src: /dev/{{ cimage_mount_dev }}{{ item.partition }}
    path: "{{ item.mountpoint }}" # Note 2.
    fstype: "{{ item.fstype }}"
    state: mounted
    fstab: /tmp/tmp.fstab # Note 1.
  loop: "{{ cimage_mount_points }}"

- name: "Mount: Debug mount results cimage_debug={{ cimage_debug }}"
  when: cimage_debug | bool
  ansible.builtin.debug:
    var: result

# Notes
#
# Note 1: It's not possible to mount a device without touching fstab. Temporary fstab is a
# workaround.
# See https://github.com/ansible-collections/ansible.posix/issues/84#issuecomment-742420345
## Note 2: Ansible module *mount* will create/remove non-existent mountpoint

# EOF
