---
- name: "Mount: Debug bsd_cimage_debug={{ bsd_cimage_debug }}"
  when: bsd_cimage_debug | bool
  vars:
    msg: |-
      bsd_cimage_mount_dir: {{ bsd_cimage_mount_dir }}
      bsd_cimage_mount_file: {{ bsd_cimage_mount_file }}
      bsd_cimage_mount_mode: {{ bsd_cimage_mount_mode }}
      bsd_cimage_mount_points_create: {{ bsd_cimage_mount_points_create }}
      bsd_cimage_mount_points:
        {{ bsd_cimage_mount_points | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Mount: Create mount points"
  when: bsd_cimage_mount_points_create | bool # Note 2.
  tags: bsd_cimage_mount_points
  ansible.builtin.file:
    state: directory
    path: "{{ item.mountpoint }}"
    mode: "{{ bsd_cimage_mount_mode }}"
  loop: "{{ bsd_cimage_mount_points }}"

- name: "Mount: Attach memory disk" # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_mdconfig.yml
  vars:
    al_mdconfig_file: "{{ bsd_cimage_mount_dir }}/{{ bsd_cimage_mount_file }}"

- name: "Mount: Set variable bsd_cimage_mount_dev"
  tags: bsd_cimage_mdconfig
  ansible.builtin.set_fact:
    bsd_cimage_mount_dev: md{{ al_mdconfig_devs[my_file]['unit'] | d('UNDEFINED') }}
  vars:
    my_file: "{{ bsd_cimage_mount_dir }}/{{ bsd_cimage_mount_file }}"

- name: "Mount: Debug {{ bsd_cimage_mount_dir ~ '/' ~ bsd_cimage_mount_file }}"
  when: bsd_cimage_debug | bool
  tags: bsd_cimage_mdconfig
  ansible.builtin.debug:
    msg: "Mounted at: {{ bsd_cimage_mount_dev }}"

- name: "Mount: Mount partitions {{ bsd_cimage_mount_dev }}"
  register: result
  ansible.posix.mount:
    src: /dev/{{ bsd_cimage_mount_dev }}{{ item.partition }}
    path: "{{ item.mountpoint }}" # Note 2.
    fstype: "{{ item.fstype }}"
    state: mounted
    fstab: /tmp/tmp.fstab # Note 1.
  loop: "{{ bsd_cimage_mount_points }}"

- name: "Mount: Debug mount results bsd_cimage_debug={{ bsd_cimage_debug }}"
  when: bsd_cimage_debug | bool
  ansible.builtin.debug:
    var: result

# Notes
#
# Note 1: It's not possible to mount a device without touching fstab. Temporary fstab is a
# workaround.
# See https://github.com/ansible-collections/ansible.posix/issues/84#issuecomment-742420345
## Note 2: Ansible module *mount* will create/remove non-existent mountpoint

# EOF
