---
- name: "Package: Install packages."
  register: result
  community.general.pkgng:
    name: "{{ cimage_packages }}"
    rootdir: "{{ cimage_pkgng_rootdir }}"
    use_globs: "{{ cimage_pkgng_use_globs }}"
    cached: "{{ cimage_pkgng_cached | d(omit) }}"
    ignore_osver: "{{ cimage_pkgng_ignore_osver | d(omit) }}"
    pkgsite: "{{ cimage_pkgng_pkgsite | d(omit) }}"
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

# EOF
