---

- name: "umount: Debug"
  vars:
    msg: |-
      bsd_cimage_mount_points
      {{ bsd_cimage_mount_points|to_yaml }}
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
  when: bsd_cimage_debug|bool

- name: "umount: Unmount"
  ansible.posix.mount:
    path: "{{ item.mountpoint }}"
    state: unmounted
    fstab: /tmp/tmp.fstab  # Note 1.
  loop: "{{ bsd_cimage_mount_points }}"
  loop_control:
    label: "{{ item.mountpoint }}"
  register: result

- name: "umount: Debug unmount results"
  ansible.builtin.debug:
    var: result
  when: bsd_cimage_debug|bool

- name: "umount: Detach memory disk"
  include_role:
    name: vbotka.ansible_lib
    tasks_from: al_mdconfig.yml
  vars:
    al_mdconfig_file: "{{ bsd_cimage_mount_dir }}/{{ bsd_cimage_mount_file }}"
    al_mdconfig_state: absent

- name: "umount: Debug detach memory disk"
  ansible.builtin.debug:
    var: al_mdconfig_devs
  when: bsd_cimage_debug|bool

# Notes
#
# Note 1: It's not possible to mount a device without touching fstab. Temporary fstab is a
# workaround.
# See https://github.com/ansible-collections/ansible.posix/issues/84#issuecomment-742420345

# EOF
...
