---
# All rights reserved (c) 2021, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Ansible playbook: pb-default.yml
#
# Description:
#
#   Downloads, mounts, and configures the system image.
#
# Requirements:
#
#   * OS: FreeBSD
#   * role: vbotka.freebsd_custom_image
#
# Example:
#
#   * Fit the variables to your needs
#   * Run the playbook
#     shell> ansible-playbook pb-default.yml
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# https://raw.githubusercontent.com/vbotka/ansible-freebsd-custom-image/master/contrib/playbook/pb-default.yml

- name: Download, mount, and configure the system image
  hosts: images.example.com

  connection: ssh
  remote_user: admin
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

  vars:
    cimage_sanity: false
    cimage_install: false
    cimage_debug: true
    cimage_debug_classified: true

    cimage_dir: /export/images/FreeBSD/live
    cimage_mount_file: FreeBSD-13.0-CURRENT-arm-armv6-RPI-B-20201231-282381aa53a-255460.img
    cimage_mount_points:
      - partition: s2a
        fstype: ufs
        mountpoint: /mnt3
    cimage_mount_path: /mnt3

  roles:
    - vbotka.freebsd_custom_image

# EOF
