---
- name: "Loaderconf: Debug cimage_debug={{ cimage_debug }}"
  when: cimage_debug | bool
  vars:
    msg: |-
      cimage_loaderconf_backup: {{ cimage_loaderconf_backup }}
      cimage_loaderconf_modules:
        {{ cimage_loaderconf_modules | to_yaml(indent=2) | indent(2) }}
      cimage_loaderconf_data:
        {{ cimage_loaderconf_data | to_nice_yaml(indent=2) | indent(2) }}
      cimage_loaderconf_sysctl:
        {{ cimage_loaderconf_sysctl | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Loaderconf: Configure {{ cimage_mount_path ~ '/boot/loader.conf' }}"
  ansible.builtin.template:
    src: loader.conf.j2
    dest: "{{ cimage_mount_path }}/boot/loader.conf"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ cimage_loaderconf_backup }}"

# EOF
