---

- name: "rcconf: Debug"
  vars:
    msg: |-
      bsd_cimage_rcconf_backup [{{ bsd_cimage_rcconf_backup }}]
      bsd_cimage_rcconf_data
      {{ bsd_cimage_rcconf_data|to_yaml }}
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
  when: bsd_cimage_debug|bool

- name: "rcconf: Configure {{ bsd_cimage_mount_path }}/etc/rc.conf"
  ansible.builtin.lineinfile:
    dest: "{{ bsd_cimage_mount_path }}/etc/rc.conf"
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}={{ item.value }}'
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ bsd_cimage_rcconf_backup }}"
  loop: "{{ bsd_cimage_rcconf_data }}"

# EOF
...
