---
- name: "Rcconf: Debug cimage_debug={{ cimage_debug }}"
  when: cimage_debug | bool
  ansible.builtin.debug:
    var: cimage_rcconf_data

- name: "Rcconf: Configure {{ cimage_mount_path ~ '/etc/rc.conf' }}"
  community.general.sysrc:
    path: "{{ cimage_mount_path }}/etc/rc.conf"
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ cimage_rcconf_data }}"

# EOF
