---
- name: "Rcconf: Debug bsd_cimage_debug={{ bsd_cimage_debug }}"
  when: bsd_cimage_debug | bool
  vars:
    msg: |-
      bsd_cimage_rcconf_backup: {{ bsd_cimage_rcconf_backup }}
      bsd_cimage_rcconf_data:
        {{ bsd_cimage_rcconf_data | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Rcconf: Configure {{ bsd_cimage_mount_path ~ '/etc/rc.conf' }}"
  ansible.builtin.lineinfile:
    dest: "{{ bsd_cimage_mount_path }}/etc/rc.conf"
    regexp: ^\s*{{ item.key }}\s*=(.*)$
    line: "{{ item.key }}={{ item.value }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ bsd_cimage_rcconf_backup }}"
  loop: "{{ bsd_cimage_rcconf_data }}"

# EOF
