---
- name: "Wpasupconf: Debug cimage_debug={{ cimage_debug }}"
  when: cimage_debug | bool
  vars:
    msg: |-
      cimage_wpasupconf_backup: {{ cimage_wpasupconf_backup }}
      cimage_wpasupconf_file: {{ cimage_wpasupconf_file }}
      cimage_wpasupconf_owner: {{ cimage_wpasupconf_owner }}
      cimage_wpasupconf_group: {{ cimage_wpasupconf_group }}
      cimage_wpasupconf_mode: {{ cimage_wpasupconf_mode }}
      cimage_wpasupconf_global:
        {{ cimage_wpasupconf_global | to_yaml(indent=2) | indent(2) }}
      {% if cimage_debug_classified %}
      cimage_wpasupconf_data:
        {{ cimage_wpasupconf_data | to_yaml(indent=2) | indent(2) }}
      {% endif %}
      cimage_wpasupconf_link: {{ cimage_wpasupconf_link }}
      cimage_wpasupconf_link_dev: {{ cimage_wpasupconf_link_dev }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Wpasupconf: Configure {{ cimage_mount_path ~ '/etc/wpasupplicant.conf' }}"
  ansible.builtin.template:
    src: wpa_supplicant.conf.j2
    dest: "{{ cimage_mount_path }}/{{ cimage_wpasupconf_file }}.{{ item.dev }}"
    owner: "{{ cimage_wpasupconf_owner }}"
    group: "{{ cimage_wpasupconf_group }}"
    mode: "{{ cimage_wpasupconf_mode }}"
    backup: "{{ cimage_wpasupconf_backup }}"
  loop: "{{ cimage_wpasupconf_data }}"
  loop_control:
    label: "{{ item.dev }}"

- name: "Wpasupconf: Link to {{ cimage_wpasupconf_file ~ '.' ~ cimage_wpasupconf_link_dev }}"
  when: cimage_wpasupconf_link | bool
  ansible.builtin.file:
    state: link
    src: wpa_supplicant.conf.{{ cimage_wpasupconf_link_dev }}
    dest: "{{ cimage_mount_path }}/{{ cimage_wpasupconf_file }}"
    force: true

# EOF
