---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Read list of files
      set_fact:
        my_files: "{{ my_files|default([]) + [item] }}"
      loop: "{{ lookup('file', 'annotation-files.txt').splitlines() }}"
    - name: Debug my_files
      debug:
        var: my_files
    - name: Create raw-annotation.yml
      template:
        src: raw-annotation.yml.j2
        dest: raw-annotation.yml
# EOF
...
